preload = /home/extraswiffy/.local/share/backgrounds/DebHypr/arc-raiders-game-1920x1080-23576.jpg

wallpaper {

    monitor = HDMI-A-1

    path = /home/extraswiffy/.local/share/backgrounds/DebHypr/arc-raiders-game-1920x1080-23576.jpg

}
