preload = ~/.local/share/backgrounds/DebHypr/after-sunset-minimal-4k-zm-3840x2160.jpg

wallpaper {
    monitor = HDMI-A-1
    path = ~/.local/share/backgrounds/DebHypr/after-sunset-minimal-4k-zm-3840x2160.jpg
}
