# DebHypr - Hyprland configuration

$mainMod = SUPER
$terminal = kitty

# Startup
exec-once = hyprpaper
exec-once = quickshell --path ~/.config/quickshell/shell.qml

# Applications
bind = SUPER, F, exec, firefox
bind = SUPER, S, exec, steam
bind = SUPER, M, exec, flatpak run com.spotify.Client
bind = SUPER, T, exec, kitty

# Window controls
bind = SUPER, C, killactive,
bind = SUPER, V, togglefloating,

# Console Mode
bind = SUPER, DELETE, exec, ~/.local/bin/desktop-to-console

# Reboot into Windows
bind = SUPER, TAB, exec, sudo -n /usr/local/sbin/reboot-to-windows

# Logout
bind = SUPER, END, exec, loginctl terminate-user $USER

# Audio
bindel = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1.0 @DEFAULT_AUDIO_SINK@ 5%+
bindel = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle

# Appearance
decoration {
    rounding = 12
    rounding_power = 2

    active_opacity = 1.0
    inactive_opacity = 1.0
}

general {
    border_size = 3

    col.active_border = rgb(708090) rgb(465A75) 45deg
    col.inactive_border = rgb(303846)
}
